### ISSUE TITLE
hid_send_feature_report & hid_write limitation on macOS

### ISSUE THREAD

**Issue by mattbeghin** [bfoz/libhid#12]
I need to write data like this to activate DualShock3 controller:
```
uint8_t dataBlob[] = { 0x42, 0x0C, 0x00, 0x00};
IOHIDDeviceSetReport(device, kIOHIDReportTypeFeature, 0xF4, dataBlob, sizeof(dataBlob));
```

If I use hid_write, it will use the first byte of the data buffer as the report_id (0xF4 in this example), and when report_id != 0 it will also send this byte in the data, because of

```
static int set_report(...)
    ...
    if (report_id == 0x0) {
        /* Not using numbered Reports.
           Don't send the report number. */
        data_to_send = data+1;
        length_to_send = length-1;
    }
   ...
```

I don't know much about HID communication but it seems I can't send the above message with libhid in its current state. Am I missing something ?

**Comment by mattbeghin** [comment]
Shouldn't the test be:
`if (report_id != 0x0) {`
?

**Comment by bfoz** [comment]
Admittedly, I haven't looked at this code in a very very long time. With that said, I can't find any of the functions that you mentioned. Am I just missing something?

**Comment by mattbeghin** [comment]
Lol, sorry that was a report for [hidapi](https://github.com/libusb/hidapi)
